name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup autotest binary
        run: |
          go build -o lint cmd/staticlint/staticlint.go

      - name: Run linters
        run: |
          ./lint ./...
